SHD: shd.c problem.c itemset.c queue.c aheap.c stdlib2.c undo.c alist.c base.c vec.c
	gcc -O3 -D_FILE2_LOAD_FROM_MEMORY_ -c shd.c # compile only object file
#	gcc -O3 -Os -s -D_FILE2_LOAD_FROM_MEMORY_ -c shd.c # compile only object file
